
package webservice.filtermail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilterWebServiceImpl", targetNamespace = "http://filtermail.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilterWebServiceImpl {


    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enableMonthFilter", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableMonthFilter")
    @ResponseWrapper(localName = "enableMonthFilterResponse", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableMonthFilterResponse")
    public void enableMonthFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "enableFilter", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableFilter")
    @ResponseWrapper(localName = "enableFilterResponse", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableFilterResponse")
    public void enableFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enableDomainFilter", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableDomainFilter")
    @ResponseWrapper(localName = "enableDomainFilterResponse", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableDomainFilterResponse")
    public void enableDomainFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enableSubjectFilter", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableSubjectFilter")
    @ResponseWrapper(localName = "enableSubjectFilterResponse", targetNamespace = "http://filtermail.webservice/", className = "webservice.filtermail.EnableSubjectFilterResponse")
    public void enableSubjectFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0)
        throws Exception_Exception
    ;

}
