
package webservice.filtermail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FilterWebServiceImplService", targetNamespace = "http://filtermail.webservice/", wsdlLocation = "http://localhost:8080/SoapWebServicesMailUtility/FilterWebServiceImpl?wsdl")
public class FilterWebServiceImplService
    extends Service
{

    private final static URL FILTERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILTERWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FILTERWEBSERVICEIMPLSERVICE_QNAME = new QName("http://filtermail.webservice/", "FilterWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoapWebServicesMailUtility/FilterWebServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILTERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FILTERWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FilterWebServiceImplService() {
        super(__getWsdlLocation(), FILTERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FilterWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILTERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FilterWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FILTERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FilterWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILTERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FilterWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilterWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FilterWebServiceImpl
     */
    @WebEndpoint(name = "FilterWebServiceImplPort")
    public FilterWebServiceImpl getFilterWebServiceImplPort() {
        return super.getPort(new QName("http://filtermail.webservice/", "FilterWebServiceImplPort"), FilterWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FilterWebServiceImpl
     */
    @WebEndpoint(name = "FilterWebServiceImplPort")
    public FilterWebServiceImpl getFilterWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://filtermail.webservice/", "FilterWebServiceImplPort"), FilterWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILTERWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FILTERWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FILTERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
